# Generated by Django 5.1 on 2024-08-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Рейтинг отзыва'),
        ),
    ]
