# Generated by Django 5.1 on 2024-08-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
    ]
